# Generated by Django 5.1.1 on 2024-11-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_orderitem_ordered_order_ordered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ordered",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
