# Generated by Django 5.1.1 on 2024-10-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksample",
            name="url",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
