# Generated by Django 5.1.1 on 2024-11-04 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
    ]
