# Generated by Django 5.1.1 on 2024-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("floor", models.IntegerField(default=1)),
                ("area", models.FloatField(default=0)),
                ("licence", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["area"],
            },
        ),
        migrations.CreateModel(
            name="Spent",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("category", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("building", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=5)),
                ("payer", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
